services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db:
    driver: local
